---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Replicated CLI tooling
        run: |
          curl -s https://api.github.com/repos/replicatedhq/replicated/releases/latest \
           | grep "browser_download_url.*$(uname | tr '[:upper:]' '[:lower:]')_amd64.tar.gz" \
           | cut -d : -f 2,3 \
           | tr -d \" \
           | cat <( echo -n "url") - \
           | curl -fsSL -K- \
           | tar xvz replicated \
           && ./replicated version
      # check for Replicated API keys
      - name: Package application
        run: ./replicated version
        env:
          REPLICATED_API_ORIGIN: https://api.replicated.com/vendor
          REPLICATED_ID_ORIGIN: https://id.replicated.com
          VENDOR_USER_EMAIL: dexter@replicated.com
          VENDOR_USER_PASSWORD: ${{ secrets.VENDOR_USER_PASSWORD }}
          REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
